[package]

name = "roman"
version = "0.0.2"
authors = ["Yann Villessuzanne <yann@miomio.fr>"]
license = "Unlicense"

description = "Convert between integers and roman numerals"
repository = "https://github.com/linfir/roman"
